"""Adiciona coluna sabores ao ItemPedido

Revision ID: 00f3268e9742
Revises: 
Create Date: 2025-06-24 16:42:02.037050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f3268e9742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sabores', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_pedido', schema=None) as batch_op:
        batch_op.drop_column('sabores')

    # ### end Alembic commands ###
