"""adiciona data_criacao ao Pedido

Revision ID: 939523cd0023
Revises: 00f3268e9742
Create Date: 2025-06-24 16:57:06.981877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939523cd0023'
down_revision = '00f3268e9742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
